# AUTO-GENERATED FILE - DO NOT EDIT
# This file was automatically generated by the XDK build tool.
# Any manual changes will be overwritten on the next generation.
defmodule Xdk.Application do
  @moduledoc false
  use Application

  @impl true
  def start(_type, _args) do
    children = [
      {Finch, name: Xdk.Finch}
    ]

    Supervisor.start_link(children, strategy: :one_for_one, name: Xdk.Supervisor)
  end
end
