# AUTO-GENERATED FILE - DO NOT EDIT
# This file was automatically generated by the XDK build tool.
# Any manual changes will be overwritten on the next generation.
defmodule Xdk.Compliance do
  @moduledoc "Auto-generated client for compliance operations"

  @doc """
  Get Compliance Jobs

  GET /2/compliance/jobs

  Retrieves a list of Compliance Jobs filtered by job type and optional status.

  """
  @spec get_jobs(Xdk.t(), opts :: keyword()) :: {:ok, map()} | {:error, Exception.t()}
  def get_jobs(client, opts \\ []) do
    query =
      [
        {"type", Keyword.get(opts, :type)},
        {"status", Keyword.get(opts, :status)},
        {"compliance_job.fields", Keyword.get(opts, :compliance_job_fields)}
      ]
      |> Enum.reject(fn {_k, v} -> is_nil(v) end)

    Xdk.request(client, :get, "/2/compliance/jobs", query: query)
  end

  @doc """
  Create Compliance Job

  POST /2/compliance/jobs

  Creates a new Compliance Job for the specified job type.

  """
  @spec create_jobs(Xdk.t()) :: {:ok, map()} | {:error, Exception.t()}
  def create_jobs(client) do
    Xdk.request(client, :post, "/2/compliance/jobs")
  end

  @doc """
  Get Compliance Job by ID

  GET /2/compliance/jobs/{id}

  Retrieves details of a specific Compliance Job by its ID.

  """
  @spec get_jobs_by_id(Xdk.t(), id :: any(), opts :: keyword()) ::
          {:ok, map()} | {:error, Exception.t()}
  def get_jobs_by_id(client, id, opts \\ []) do
    query =
      [
        {"compliance_job.fields", Keyword.get(opts, :compliance_job_fields)}
      ]
      |> Enum.reject(fn {_k, v} -> is_nil(v) end)

    Xdk.request(client, :get, "/2/compliance/jobs/{id}",
      params: %{
        "id" => id
      },
      query: query
    )
  end
end
