# AUTO-GENERATED FILE - DO NOT EDIT
# This file was automatically generated by the XDK build tool.
# Any manual changes will be overwritten on the next generation.
defmodule Xdk.Errors do
  use Splode,
    error_classes: [
      api: Xdk.Errors.Api,
      transport: Xdk.Errors.Transport,
      unknown: Xdk.Errors.Unknown
    ],
    unknown_error: Xdk.Errors.Unknown.UnknownError
end

defmodule Xdk.Errors.Api do
  use Splode.ErrorClass, class: :api
end

defmodule Xdk.Errors.Transport do
  use Splode.ErrorClass, class: :transport
end

defmodule Xdk.Errors.Unknown do
  use Splode.ErrorClass, class: :unknown
end

defmodule Xdk.Errors.Unknown.UnknownError do
  use Splode.Error, fields: [:error], class: :unknown

  def message(%{error: error}) do
    if is_binary(error) do
      error
    else
      inspect(error)
    end
  end
end

defmodule Xdk.Errors.ApiError do
  use Splode.Error, fields: [:status, :body], class: :api

  def message(%{status: status, body: body}) do
    "X API error (HTTP #{status}): #{inspect(body)}"
  end
end

defmodule Xdk.Errors.TransportError do
  use Splode.Error, fields: [:reason], class: :transport

  def message(%{reason: reason}) do
    "Transport error: #{inspect(reason)}"
  end
end
