# AUTO-GENERATED FILE - DO NOT EDIT
# This file was automatically generated by the XDK build tool.
# Any manual changes will be overwritten on the next generation.
defmodule Xdk.General do
  @moduledoc "Auto-generated client for general operations"

  @doc """
  Get OpenAPI Spec.

  GET /2/openapi.json

  Retrieves the full OpenAPI Specification in JSON format. (See https://github.com/OAI/OpenAPI-Specification/blob/master/README.md)

  """
  @spec get_open_api_spec(Xdk.t()) :: {:ok, map()} | {:error, Xdk.Errors.error()}

  def get_open_api_spec(client) do
    Xdk.request(client, :get, "/2/openapi.json")
  end
end
