# AUTO-GENERATED FILE - DO NOT EDIT
# This file was automatically generated by the XDK build tool.
# Any manual changes will be overwritten on the next generation.
defmodule Xdk.Marketplace do
  @moduledoc "Auto-generated client for marketplace operations"

  @doc """
  Get marketplace handle availability

  GET /2/marketplace/handles/{handle}/availability

  Returns marketplace availability state and a redirect URL for a handle.

  """
  @spec get_handle_availability(Xdk.t(), handle :: String.t(), opts :: keyword()) ::
          {:ok, map()} | {:error, Exception.t()}
  def get_handle_availability(client, handle, opts \\ []) do
    query =
      [
        {"marketplace_handle_availability.fields",
         Keyword.get(opts, :marketplace_handle_availability_fields)}
      ]
      |> Enum.reject(fn {_k, v} -> is_nil(v) end)

    Xdk.request(client, :get, "/2/marketplace/handles/{handle}/availability",
      params: %{
        "handle" => handle
      },
      query: query
    )
  end
end
