# AUTO-GENERATED FILE - DO NOT EDIT
# This file was automatically generated by the XDK build tool.
# Any manual changes will be overwritten on the next generation.
defmodule Xdk.News do
  @moduledoc "Auto-generated client for news operations"

  @doc """
  Search News

  GET /2/news/search

  Retrieves a list of News stories matching the specified search query.

  """
  @spec search(Xdk.t(), opts :: keyword()) :: {:ok, map()} | {:error, Xdk.Errors.error()}

  def search(client, opts \\ []) do
    query =
      [
        {"query", Keyword.get(opts, :query)},
        {"max_results", Keyword.get(opts, :max_results)},
        {"max_age_hours", Keyword.get(opts, :max_age_hours)},
        {"news.fields", Keyword.get(opts, :news_fields)}
      ]
      |> Xdk.Query.build()

    Xdk.request(client, :get, "/2/news/search", query: query)
  end

  @doc """
  Get news stories by ID

  GET /2/news/{id}

  Retrieves news story by its ID.

  """
  @spec get(Xdk.t(), id :: String.t(), opts :: keyword()) ::
          {:ok, map()} | {:error, Xdk.Errors.error()}

  def get(client, id, opts \\ []) do
    query =
      [
        {"news.fields", Keyword.get(opts, :news_fields)}
      ]
      |> Xdk.Query.build()

    Xdk.request(client, :get, "/2/news/{id}",
      params: %{
        "id" => id
      },
      query: query
    )
  end
end
