# AUTO-GENERATED FILE - DO NOT EDIT
# This file was automatically generated by the XDK build tool.
# Any manual changes will be overwritten on the next generation.
defmodule Xdk.Trends do
  @moduledoc "Auto-generated client for trends operations"

  @doc """
  Get personalized Trends

  GET /2/users/personalized_trends

  Retrieves personalized trending topics for the authenticated user.

  """
  @spec get_personalized(Xdk.t(), opts :: keyword()) ::
          {:ok, map()} | {:error, Xdk.Errors.error()}

  def get_personalized(client, opts \\ []) do
    query =
      [
        {"personalized_trend.fields", Keyword.get(opts, :personalized_trend_fields)}
      ]
      |> Xdk.Query.build()

    Xdk.request(client, :get, "/2/users/personalized_trends", query: query)
  end

  @doc """
  Get Trends by WOEID

  GET /2/trends/by/woeid/{woeid}

  Retrieves trending topics for a specific location identified by its WOEID.

  """
  @spec get_by_woeid(Xdk.t(), woeid :: integer(), opts :: keyword()) ::
          {:ok, map()} | {:error, Xdk.Errors.error()}

  def get_by_woeid(client, woeid, opts \\ []) do
    query =
      [
        {"max_trends", Keyword.get(opts, :max_trends)},
        {"trend.fields", Keyword.get(opts, :trend_fields)}
      ]
      |> Xdk.Query.build()

    Xdk.request(client, :get, "/2/trends/by/woeid/{woeid}",
      params: %{
        "woeid" => woeid
      },
      query: query
    )
  end
end
