# AUTO-GENERATED FILE - DO NOT EDIT
# This file was automatically generated by the XDK build tool.
# Any manual changes will be overwritten on the next generation.
defmodule Xdk.MixProject do
  use Mix.Project

  def project do
    [
      app: :xdk,
      version: "0.1.0",
      elixir: "~> 1.15",
      start_permanent: Mix.env() == :prod,
      deps: deps()
    ]
  end

  def application do
    [
      extra_applications: [:logger]
    ]
  end

  defp deps do
    [
      {:finch, "~> 0.19"},
      {:jason, "~> 1.4"},
      {:splode, "~> 0.2"},
      {:oauther, "~> 1.3"},
      {:bypass, "~> 2.1", only: :test},
      {:dotenvy, "~> 0.8", only: [:dev, :test]}
    ]
  end
end
