# AUTO-GENERATED FILE - DO NOT EDIT
# This file was automatically generated by the XDK build tool.
# Any manual changes will be overwritten on the next generation.
defmodule Xdk.AccountActivityTest do
  use ExUnit.Case, async: true

  describe "module structure" do
    test "module exists" do
      assert Code.ensure_loaded?(Xdk.AccountActivity)
    end

    test "validate_subscription function exists" do
      Code.ensure_loaded!(Xdk.AccountActivity)
      assert function_exported?(Xdk.AccountActivity, :validate_subscription, 2)
    end

    test "create_subscription function exists" do
      Code.ensure_loaded!(Xdk.AccountActivity)
      assert function_exported?(Xdk.AccountActivity, :create_subscription, 2)
    end

    test "create_replay_job function exists" do
      Code.ensure_loaded!(Xdk.AccountActivity)

      assert function_exported?(Xdk.AccountActivity, :create_replay_job, 2) or
               function_exported?(Xdk.AccountActivity, :create_replay_job, 3)
    end

    test "get_subscription_count function exists" do
      Code.ensure_loaded!(Xdk.AccountActivity)
      assert function_exported?(Xdk.AccountActivity, :get_subscription_count, 1)
    end

    test "get_subscriptions function exists" do
      Code.ensure_loaded!(Xdk.AccountActivity)
      assert function_exported?(Xdk.AccountActivity, :get_subscriptions, 2)
    end

    test "delete_subscription function exists" do
      Code.ensure_loaded!(Xdk.AccountActivity)
      assert function_exported?(Xdk.AccountActivity, :delete_subscription, 3)
    end
  end
end
