# AUTO-GENERATED FILE - DO NOT EDIT
# This file was automatically generated by the XDK build tool.
# Any manual changes will be overwritten on the next generation.
defmodule Xdk.ActivityTest do
  use ExUnit.Case, async: true

  describe "module structure" do
    test "module exists" do
      assert Code.ensure_loaded?(Xdk.Activity)
    end

    test "stream function exists" do
      Code.ensure_loaded!(Xdk.Activity)

      assert function_exported?(Xdk.Activity, :stream, 1) or
               function_exported?(Xdk.Activity, :stream, 2)
    end

    test "get_subscriptions function exists" do
      Code.ensure_loaded!(Xdk.Activity)

      assert function_exported?(Xdk.Activity, :get_subscriptions, 1) or
               function_exported?(Xdk.Activity, :get_subscriptions, 2)
    end

    test "create_subscription function exists" do
      Code.ensure_loaded!(Xdk.Activity)
      assert function_exported?(Xdk.Activity, :create_subscription, 1)
    end

    test "update_subscription function exists" do
      Code.ensure_loaded!(Xdk.Activity)
      assert function_exported?(Xdk.Activity, :update_subscription, 2)
    end

    test "delete_subscription function exists" do
      Code.ensure_loaded!(Xdk.Activity)
      assert function_exported?(Xdk.Activity, :delete_subscription, 2)
    end
  end
end
