# AUTO-GENERATED FILE - DO NOT EDIT
# This file was automatically generated by the XDK build tool.
# Any manual changes will be overwritten on the next generation.
defmodule Xdk.ChatTest do
  use ExUnit.Case, async: true

  describe "module structure" do
    test "module exists" do
      assert Code.ensure_loaded?(Xdk.Chat)
    end

    test "get_conversation function exists" do
      Code.ensure_loaded!(Xdk.Chat)

      assert function_exported?(Xdk.Chat, :get_conversation, 2) or
               function_exported?(Xdk.Chat, :get_conversation, 3)
    end

    test "get_user_public_keys function exists" do
      Code.ensure_loaded!(Xdk.Chat)

      assert function_exported?(Xdk.Chat, :get_user_public_keys, 2) or
               function_exported?(Xdk.Chat, :get_user_public_keys, 3)
    end

    test "add_user_public_key function exists" do
      Code.ensure_loaded!(Xdk.Chat)
      assert function_exported?(Xdk.Chat, :add_user_public_key, 2)
    end

    test "send_message function exists" do
      Code.ensure_loaded!(Xdk.Chat)
      assert function_exported?(Xdk.Chat, :send_message, 2)
    end

    test "get_conversations function exists" do
      Code.ensure_loaded!(Xdk.Chat)

      assert function_exported?(Xdk.Chat, :get_conversations, 1) or
               function_exported?(Xdk.Chat, :get_conversations, 2)
    end
  end
end
