# AUTO-GENERATED FILE - DO NOT EDIT
# This file was automatically generated by the XDK build tool.
# Any manual changes will be overwritten on the next generation.
defmodule Xdk.CommunitiesTest do
  use ExUnit.Case, async: true

  describe "module structure" do
    test "module exists" do
      assert Code.ensure_loaded?(Xdk.Communities)
    end

    test "search function exists" do
      Code.ensure_loaded!(Xdk.Communities)

      assert function_exported?(Xdk.Communities, :search, 1) or
               function_exported?(Xdk.Communities, :search, 2)
    end

    test "get_by_id function exists" do
      Code.ensure_loaded!(Xdk.Communities)

      assert function_exported?(Xdk.Communities, :get_by_id, 2) or
               function_exported?(Xdk.Communities, :get_by_id, 3)
    end
  end
end
