# AUTO-GENERATED FILE - DO NOT EDIT
# This file was automatically generated by the XDK build tool.
# Any manual changes will be overwritten on the next generation.
defmodule Xdk.CommunityNotesTest do
  use ExUnit.Case, async: true

  describe "module structure" do
    test "module exists" do
      assert Code.ensure_loaded?(Xdk.CommunityNotes)
    end

    test "create function exists" do
      Code.ensure_loaded!(Xdk.CommunityNotes)
      assert function_exported?(Xdk.CommunityNotes, :create, 1)
    end

    test "search_eligible_posts function exists" do
      Code.ensure_loaded!(Xdk.CommunityNotes)

      assert function_exported?(Xdk.CommunityNotes, :search_eligible_posts, 1) or
               function_exported?(Xdk.CommunityNotes, :search_eligible_posts, 2)
    end

    test "search_written function exists" do
      Code.ensure_loaded!(Xdk.CommunityNotes)

      assert function_exported?(Xdk.CommunityNotes, :search_written, 1) or
               function_exported?(Xdk.CommunityNotes, :search_written, 2)
    end

    test "delete function exists" do
      Code.ensure_loaded!(Xdk.CommunityNotes)
      assert function_exported?(Xdk.CommunityNotes, :delete, 2)
    end

    test "evaluate function exists" do
      Code.ensure_loaded!(Xdk.CommunityNotes)
      assert function_exported?(Xdk.CommunityNotes, :evaluate, 1)
    end
  end
end
