# AUTO-GENERATED FILE - DO NOT EDIT
# This file was automatically generated by the XDK build tool.
# Any manual changes will be overwritten on the next generation.
defmodule Xdk.ComplianceTest do
  use ExUnit.Case, async: true

  describe "module structure" do
    test "module exists" do
      assert Code.ensure_loaded?(Xdk.Compliance)
    end

    test "get_jobs function exists" do
      Code.ensure_loaded!(Xdk.Compliance)

      assert function_exported?(Xdk.Compliance, :get_jobs, 1) or
               function_exported?(Xdk.Compliance, :get_jobs, 2)
    end

    test "create_jobs function exists" do
      Code.ensure_loaded!(Xdk.Compliance)
      assert function_exported?(Xdk.Compliance, :create_jobs, 1)
    end

    test "get_jobs_by_id function exists" do
      Code.ensure_loaded!(Xdk.Compliance)

      assert function_exported?(Xdk.Compliance, :get_jobs_by_id, 2) or
               function_exported?(Xdk.Compliance, :get_jobs_by_id, 3)
    end
  end
end
