# AUTO-GENERATED FILE - DO NOT EDIT
# This file was automatically generated by the XDK build tool.
# Any manual changes will be overwritten on the next generation.
defmodule Xdk.ConnectionsTest do
  use ExUnit.Case, async: true

  describe "module structure" do
    test "module exists" do
      assert Code.ensure_loaded?(Xdk.Connections)
    end

    test "delete_all function exists" do
      Code.ensure_loaded!(Xdk.Connections)
      assert function_exported?(Xdk.Connections, :delete_all, 1)
    end

    test "delete_by_endpoint function exists" do
      Code.ensure_loaded!(Xdk.Connections)
      assert function_exported?(Xdk.Connections, :delete_by_endpoint, 2)
    end

    test "get_connection_history function exists" do
      Code.ensure_loaded!(Xdk.Connections)

      assert function_exported?(Xdk.Connections, :get_connection_history, 1) or
               function_exported?(Xdk.Connections, :get_connection_history, 2)
    end

    test "delete_by_uuids function exists" do
      Code.ensure_loaded!(Xdk.Connections)
      assert function_exported?(Xdk.Connections, :delete_by_uuids, 1)
    end
  end
end
