# AUTO-GENERATED FILE - DO NOT EDIT
# This file was automatically generated by the XDK build tool.
# Any manual changes will be overwritten on the next generation.
defmodule Xdk.DirectMessagesTest do
  use ExUnit.Case, async: true

  describe "module structure" do
    test "module exists" do
      assert Code.ensure_loaded?(Xdk.DirectMessages)
    end

    test "get_events function exists" do
      Code.ensure_loaded!(Xdk.DirectMessages)

      assert function_exported?(Xdk.DirectMessages, :get_events, 1) or
               function_exported?(Xdk.DirectMessages, :get_events, 2)
    end

    test "get_events_by_conversation_id function exists" do
      Code.ensure_loaded!(Xdk.DirectMessages)

      assert function_exported?(Xdk.DirectMessages, :get_events_by_conversation_id, 2) or
               function_exported?(Xdk.DirectMessages, :get_events_by_conversation_id, 3)
    end

    test "get_events_by_id function exists" do
      Code.ensure_loaded!(Xdk.DirectMessages)

      assert function_exported?(Xdk.DirectMessages, :get_events_by_id, 2) or
               function_exported?(Xdk.DirectMessages, :get_events_by_id, 3)
    end

    test "delete_events function exists" do
      Code.ensure_loaded!(Xdk.DirectMessages)
      assert function_exported?(Xdk.DirectMessages, :delete_events, 2)
    end

    test "create_conversation function exists" do
      Code.ensure_loaded!(Xdk.DirectMessages)
      assert function_exported?(Xdk.DirectMessages, :create_conversation, 1)
    end

    test "create_by_participant_id function exists" do
      Code.ensure_loaded!(Xdk.DirectMessages)
      assert function_exported?(Xdk.DirectMessages, :create_by_participant_id, 2)
    end

    test "get_events_by_participant_id function exists" do
      Code.ensure_loaded!(Xdk.DirectMessages)

      assert function_exported?(Xdk.DirectMessages, :get_events_by_participant_id, 2) or
               function_exported?(Xdk.DirectMessages, :get_events_by_participant_id, 3)
    end

    test "create_by_conversation_id function exists" do
      Code.ensure_loaded!(Xdk.DirectMessages)
      assert function_exported?(Xdk.DirectMessages, :create_by_conversation_id, 2)
    end
  end
end
