# AUTO-GENERATED FILE - DO NOT EDIT
# This file was automatically generated by the XDK build tool.
# Any manual changes will be overwritten on the next generation.
defmodule Xdk.GeneralTest do
  use ExUnit.Case, async: true

  describe "module structure" do
    test "module exists" do
      assert Code.ensure_loaded?(Xdk.General)
    end

    test "get_open_api_spec function exists" do
      Code.ensure_loaded!(Xdk.General)
      assert function_exported?(Xdk.General, :get_open_api_spec, 1)
    end
  end
end
