# AUTO-GENERATED FILE - DO NOT EDIT
# This file was automatically generated by the XDK build tool.
# Any manual changes will be overwritten on the next generation.
defmodule Xdk.ListsTest do
  use ExUnit.Case, async: true

  describe "module structure" do
    test "module exists" do
      assert Code.ensure_loaded?(Xdk.Lists)
    end

    test "get_followers function exists" do
      Code.ensure_loaded!(Xdk.Lists)

      assert function_exported?(Xdk.Lists, :get_followers, 2) or
               function_exported?(Xdk.Lists, :get_followers, 3)
    end

    test "get_posts function exists" do
      Code.ensure_loaded!(Xdk.Lists)

      assert function_exported?(Xdk.Lists, :get_posts, 2) or
               function_exported?(Xdk.Lists, :get_posts, 3)
    end

    test "remove_member_by_user_id function exists" do
      Code.ensure_loaded!(Xdk.Lists)
      assert function_exported?(Xdk.Lists, :remove_member_by_user_id, 3)
    end

    test "get_members function exists" do
      Code.ensure_loaded!(Xdk.Lists)

      assert function_exported?(Xdk.Lists, :get_members, 2) or
               function_exported?(Xdk.Lists, :get_members, 3)
    end

    test "add_member function exists" do
      Code.ensure_loaded!(Xdk.Lists)
      assert function_exported?(Xdk.Lists, :add_member, 2)
    end

    test "get_by_id function exists" do
      Code.ensure_loaded!(Xdk.Lists)

      assert function_exported?(Xdk.Lists, :get_by_id, 2) or
               function_exported?(Xdk.Lists, :get_by_id, 3)
    end

    test "update function exists" do
      Code.ensure_loaded!(Xdk.Lists)
      assert function_exported?(Xdk.Lists, :update, 2)
    end

    test "delete function exists" do
      Code.ensure_loaded!(Xdk.Lists)
      assert function_exported?(Xdk.Lists, :delete, 2)
    end

    test "create function exists" do
      Code.ensure_loaded!(Xdk.Lists)
      assert function_exported?(Xdk.Lists, :create, 1)
    end
  end
end
