# AUTO-GENERATED FILE - DO NOT EDIT
# This file was automatically generated by the XDK build tool.
# Any manual changes will be overwritten on the next generation.
defmodule Xdk.MarketplaceTest do
  use ExUnit.Case, async: true

  describe "module structure" do
    test "module exists" do
      assert Code.ensure_loaded?(Xdk.Marketplace)
    end

    test "get_handle_availability function exists" do
      Code.ensure_loaded!(Xdk.Marketplace)

      assert function_exported?(Xdk.Marketplace, :get_handle_availability, 2) or
               function_exported?(Xdk.Marketplace, :get_handle_availability, 3)
    end
  end
end
