# AUTO-GENERATED FILE - DO NOT EDIT
# This file was automatically generated by the XDK build tool.
# Any manual changes will be overwritten on the next generation.
defmodule Xdk.MediaTest do
  use ExUnit.Case, async: true

  describe "module structure" do
    test "module exists" do
      assert Code.ensure_loaded?(Xdk.Media)
    end

    test "get_upload_status function exists" do
      Code.ensure_loaded!(Xdk.Media)

      assert function_exported?(Xdk.Media, :get_upload_status, 1) or
               function_exported?(Xdk.Media, :get_upload_status, 2)
    end

    test "upload function exists" do
      Code.ensure_loaded!(Xdk.Media)
      assert function_exported?(Xdk.Media, :upload, 1)
    end

    test "finalize_upload function exists" do
      Code.ensure_loaded!(Xdk.Media)
      assert function_exported?(Xdk.Media, :finalize_upload, 2)
    end

    test "create_subtitles function exists" do
      Code.ensure_loaded!(Xdk.Media)
      assert function_exported?(Xdk.Media, :create_subtitles, 1)
    end

    test "delete_subtitles function exists" do
      Code.ensure_loaded!(Xdk.Media)
      assert function_exported?(Xdk.Media, :delete_subtitles, 1)
    end

    test "append_upload function exists" do
      Code.ensure_loaded!(Xdk.Media)
      assert function_exported?(Xdk.Media, :append_upload, 2)
    end

    test "initialize_upload function exists" do
      Code.ensure_loaded!(Xdk.Media)
      assert function_exported?(Xdk.Media, :initialize_upload, 1)
    end

    test "get_by_key function exists" do
      Code.ensure_loaded!(Xdk.Media)

      assert function_exported?(Xdk.Media, :get_by_key, 2) or
               function_exported?(Xdk.Media, :get_by_key, 3)
    end

    test "get_by_keys function exists" do
      Code.ensure_loaded!(Xdk.Media)

      assert function_exported?(Xdk.Media, :get_by_keys, 1) or
               function_exported?(Xdk.Media, :get_by_keys, 2)
    end

    test "create_metadata function exists" do
      Code.ensure_loaded!(Xdk.Media)
      assert function_exported?(Xdk.Media, :create_metadata, 1)
    end

    test "get_analytics function exists" do
      Code.ensure_loaded!(Xdk.Media)

      assert function_exported?(Xdk.Media, :get_analytics, 1) or
               function_exported?(Xdk.Media, :get_analytics, 2)
    end
  end
end
