# AUTO-GENERATED FILE - DO NOT EDIT
# This file was automatically generated by the XDK build tool.
# Any manual changes will be overwritten on the next generation.
defmodule Xdk.NewsTest do
  use ExUnit.Case, async: true

  describe "module structure" do
    test "module exists" do
      assert Code.ensure_loaded?(Xdk.News)
    end

    test "get function exists" do
      Code.ensure_loaded!(Xdk.News)
      assert function_exported?(Xdk.News, :get, 2) or function_exported?(Xdk.News, :get, 3)
    end

    test "search function exists" do
      Code.ensure_loaded!(Xdk.News)
      assert function_exported?(Xdk.News, :search, 1) or function_exported?(Xdk.News, :search, 2)
    end
  end
end
