# AUTO-GENERATED FILE - DO NOT EDIT
# This file was automatically generated by the XDK build tool.
# Any manual changes will be overwritten on the next generation.
defmodule Xdk.PostsTest do
  use ExUnit.Case, async: true

  describe "module structure" do
    test "module exists" do
      assert Code.ensure_loaded?(Xdk.Posts)
    end

    test "get_quoted function exists" do
      Code.ensure_loaded!(Xdk.Posts)

      assert function_exported?(Xdk.Posts, :get_quoted, 2) or
               function_exported?(Xdk.Posts, :get_quoted, 3)
    end

    test "get_insights28hr function exists" do
      Code.ensure_loaded!(Xdk.Posts)

      assert function_exported?(Xdk.Posts, :get_insights28hr, 1) or
               function_exported?(Xdk.Posts, :get_insights28hr, 2)
    end

    test "get_counts_recent function exists" do
      Code.ensure_loaded!(Xdk.Posts)

      assert function_exported?(Xdk.Posts, :get_counts_recent, 1) or
               function_exported?(Xdk.Posts, :get_counts_recent, 2)
    end

    test "hide_reply function exists" do
      Code.ensure_loaded!(Xdk.Posts)
      assert function_exported?(Xdk.Posts, :hide_reply, 2)
    end

    test "get_by_id function exists" do
      Code.ensure_loaded!(Xdk.Posts)

      assert function_exported?(Xdk.Posts, :get_by_id, 2) or
               function_exported?(Xdk.Posts, :get_by_id, 3)
    end

    test "delete function exists" do
      Code.ensure_loaded!(Xdk.Posts)
      assert function_exported?(Xdk.Posts, :delete, 2)
    end

    test "search_all function exists" do
      Code.ensure_loaded!(Xdk.Posts)

      assert function_exported?(Xdk.Posts, :search_all, 1) or
               function_exported?(Xdk.Posts, :search_all, 2)
    end

    test "get_reposted_by function exists" do
      Code.ensure_loaded!(Xdk.Posts)

      assert function_exported?(Xdk.Posts, :get_reposted_by, 2) or
               function_exported?(Xdk.Posts, :get_reposted_by, 3)
    end

    test "get_by_ids function exists" do
      Code.ensure_loaded!(Xdk.Posts)

      assert function_exported?(Xdk.Posts, :get_by_ids, 1) or
               function_exported?(Xdk.Posts, :get_by_ids, 2)
    end

    test "create function exists" do
      Code.ensure_loaded!(Xdk.Posts)
      assert function_exported?(Xdk.Posts, :create, 1)
    end

    test "search_recent function exists" do
      Code.ensure_loaded!(Xdk.Posts)

      assert function_exported?(Xdk.Posts, :search_recent, 1) or
               function_exported?(Xdk.Posts, :search_recent, 2)
    end

    test "get_counts_all function exists" do
      Code.ensure_loaded!(Xdk.Posts)

      assert function_exported?(Xdk.Posts, :get_counts_all, 1) or
               function_exported?(Xdk.Posts, :get_counts_all, 2)
    end

    test "get_liking_users function exists" do
      Code.ensure_loaded!(Xdk.Posts)

      assert function_exported?(Xdk.Posts, :get_liking_users, 2) or
               function_exported?(Xdk.Posts, :get_liking_users, 3)
    end

    test "get_insights_historical function exists" do
      Code.ensure_loaded!(Xdk.Posts)

      assert function_exported?(Xdk.Posts, :get_insights_historical, 1) or
               function_exported?(Xdk.Posts, :get_insights_historical, 2)
    end

    test "get_analytics function exists" do
      Code.ensure_loaded!(Xdk.Posts)

      assert function_exported?(Xdk.Posts, :get_analytics, 1) or
               function_exported?(Xdk.Posts, :get_analytics, 2)
    end

    test "get_reposts function exists" do
      Code.ensure_loaded!(Xdk.Posts)

      assert function_exported?(Xdk.Posts, :get_reposts, 2) or
               function_exported?(Xdk.Posts, :get_reposts, 3)
    end
  end
end
