# AUTO-GENERATED FILE - DO NOT EDIT
# This file was automatically generated by the XDK build tool.
# Any manual changes will be overwritten on the next generation.
defmodule Xdk.SpacesTest do
  use ExUnit.Case, async: true

  describe "module structure" do
    test "module exists" do
      assert Code.ensure_loaded?(Xdk.Spaces)
    end

    test "get_by_id function exists" do
      Code.ensure_loaded!(Xdk.Spaces)

      assert function_exported?(Xdk.Spaces, :get_by_id, 2) or
               function_exported?(Xdk.Spaces, :get_by_id, 3)
    end

    test "get_buyers function exists" do
      Code.ensure_loaded!(Xdk.Spaces)

      assert function_exported?(Xdk.Spaces, :get_buyers, 2) or
               function_exported?(Xdk.Spaces, :get_buyers, 3)
    end

    test "get_by_creator_ids function exists" do
      Code.ensure_loaded!(Xdk.Spaces)

      assert function_exported?(Xdk.Spaces, :get_by_creator_ids, 1) or
               function_exported?(Xdk.Spaces, :get_by_creator_ids, 2)
    end

    test "search function exists" do
      Code.ensure_loaded!(Xdk.Spaces)

      assert function_exported?(Xdk.Spaces, :search, 1) or
               function_exported?(Xdk.Spaces, :search, 2)
    end

    test "get_posts function exists" do
      Code.ensure_loaded!(Xdk.Spaces)

      assert function_exported?(Xdk.Spaces, :get_posts, 2) or
               function_exported?(Xdk.Spaces, :get_posts, 3)
    end

    test "get_by_ids function exists" do
      Code.ensure_loaded!(Xdk.Spaces)

      assert function_exported?(Xdk.Spaces, :get_by_ids, 1) or
               function_exported?(Xdk.Spaces, :get_by_ids, 2)
    end
  end
end
