# AUTO-GENERATED FILE - DO NOT EDIT
# This file was automatically generated by the XDK build tool.
# Any manual changes will be overwritten on the next generation.
defmodule Xdk.TrendsTest do
  use ExUnit.Case, async: true

  describe "module structure" do
    test "module exists" do
      assert Code.ensure_loaded?(Xdk.Trends)
    end

    test "get_personalized function exists" do
      Code.ensure_loaded!(Xdk.Trends)

      assert function_exported?(Xdk.Trends, :get_personalized, 1) or
               function_exported?(Xdk.Trends, :get_personalized, 2)
    end

    test "get_by_woeid function exists" do
      Code.ensure_loaded!(Xdk.Trends)

      assert function_exported?(Xdk.Trends, :get_by_woeid, 2) or
               function_exported?(Xdk.Trends, :get_by_woeid, 3)
    end
  end
end
