# AUTO-GENERATED FILE - DO NOT EDIT
# This file was automatically generated by the XDK build tool.
# Any manual changes will be overwritten on the next generation.
defmodule Xdk.UsageTest do
  use ExUnit.Case, async: true

  describe "module structure" do
    test "module exists" do
      assert Code.ensure_loaded?(Xdk.Usage)
    end

    test "get function exists" do
      Code.ensure_loaded!(Xdk.Usage)
      assert function_exported?(Xdk.Usage, :get, 1) or function_exported?(Xdk.Usage, :get, 2)
    end
  end
end
