# AUTO-GENERATED FILE - DO NOT EDIT
# This file was automatically generated by the XDK build tool.
# Any manual changes will be overwritten on the next generation.
defmodule Xdk.UsersTest do
  use ExUnit.Case, async: true

  describe "module structure" do
    test "module exists" do
      assert Code.ensure_loaded?(Xdk.Users)
    end

    test "block_dms function exists" do
      Code.ensure_loaded!(Xdk.Users)
      assert function_exported?(Xdk.Users, :block_dms, 2)
    end

    test "like_post function exists" do
      Code.ensure_loaded!(Xdk.Users)
      assert function_exported?(Xdk.Users, :like_post, 2)
    end

    test "unrepost_post function exists" do
      Code.ensure_loaded!(Xdk.Users)
      assert function_exported?(Xdk.Users, :unrepost_post, 3)
    end

    test "unfollow_user function exists" do
      Code.ensure_loaded!(Xdk.Users)
      assert function_exported?(Xdk.Users, :unfollow_user, 3)
    end

    test "get_blocking function exists" do
      Code.ensure_loaded!(Xdk.Users)

      assert function_exported?(Xdk.Users, :get_blocking, 2) or
               function_exported?(Xdk.Users, :get_blocking, 3)
    end

    test "unpin_list function exists" do
      Code.ensure_loaded!(Xdk.Users)
      assert function_exported?(Xdk.Users, :unpin_list, 3)
    end

    test "get_owned_lists function exists" do
      Code.ensure_loaded!(Xdk.Users)

      assert function_exported?(Xdk.Users, :get_owned_lists, 2) or
               function_exported?(Xdk.Users, :get_owned_lists, 3)
    end

    test "get_liked_posts function exists" do
      Code.ensure_loaded!(Xdk.Users)

      assert function_exported?(Xdk.Users, :get_liked_posts, 2) or
               function_exported?(Xdk.Users, :get_liked_posts, 3)
    end

    test "get_list_memberships function exists" do
      Code.ensure_loaded!(Xdk.Users)

      assert function_exported?(Xdk.Users, :get_list_memberships, 2) or
               function_exported?(Xdk.Users, :get_list_memberships, 3)
    end

    test "get_posts function exists" do
      Code.ensure_loaded!(Xdk.Users)

      assert function_exported?(Xdk.Users, :get_posts, 2) or
               function_exported?(Xdk.Users, :get_posts, 3)
    end

    test "get_pinned_lists function exists" do
      Code.ensure_loaded!(Xdk.Users)

      assert function_exported?(Xdk.Users, :get_pinned_lists, 2) or
               function_exported?(Xdk.Users, :get_pinned_lists, 3)
    end

    test "pin_list function exists" do
      Code.ensure_loaded!(Xdk.Users)
      assert function_exported?(Xdk.Users, :pin_list, 2)
    end

    test "get_affiliates function exists" do
      Code.ensure_loaded!(Xdk.Users)

      assert function_exported?(Xdk.Users, :get_affiliates, 2) or
               function_exported?(Xdk.Users, :get_affiliates, 3)
    end

    test "get_following function exists" do
      Code.ensure_loaded!(Xdk.Users)

      assert function_exported?(Xdk.Users, :get_following, 2) or
               function_exported?(Xdk.Users, :get_following, 3)
    end

    test "follow_user function exists" do
      Code.ensure_loaded!(Xdk.Users)
      assert function_exported?(Xdk.Users, :follow_user, 2)
    end

    test "repost_post function exists" do
      Code.ensure_loaded!(Xdk.Users)
      assert function_exported?(Xdk.Users, :repost_post, 2)
    end

    test "get_bookmark_folders function exists" do
      Code.ensure_loaded!(Xdk.Users)

      assert function_exported?(Xdk.Users, :get_bookmark_folders, 2) or
               function_exported?(Xdk.Users, :get_bookmark_folders, 3)
    end

    test "get_by_id function exists" do
      Code.ensure_loaded!(Xdk.Users)

      assert function_exported?(Xdk.Users, :get_by_id, 2) or
               function_exported?(Xdk.Users, :get_by_id, 3)
    end

    test "get_by_usernames function exists" do
      Code.ensure_loaded!(Xdk.Users)

      assert function_exported?(Xdk.Users, :get_by_usernames, 1) or
               function_exported?(Xdk.Users, :get_by_usernames, 2)
    end

    test "get_by_ids function exists" do
      Code.ensure_loaded!(Xdk.Users)

      assert function_exported?(Xdk.Users, :get_by_ids, 1) or
               function_exported?(Xdk.Users, :get_by_ids, 2)
    end

    test "get_mentions function exists" do
      Code.ensure_loaded!(Xdk.Users)

      assert function_exported?(Xdk.Users, :get_mentions, 2) or
               function_exported?(Xdk.Users, :get_mentions, 3)
    end

    test "get_bookmarks_by_folder_id function exists" do
      Code.ensure_loaded!(Xdk.Users)
      assert function_exported?(Xdk.Users, :get_bookmarks_by_folder_id, 3)
    end

    test "unmute_user function exists" do
      Code.ensure_loaded!(Xdk.Users)
      assert function_exported?(Xdk.Users, :unmute_user, 3)
    end

    test "unblock_dms function exists" do
      Code.ensure_loaded!(Xdk.Users)
      assert function_exported?(Xdk.Users, :unblock_dms, 2)
    end

    test "get_muting function exists" do
      Code.ensure_loaded!(Xdk.Users)

      assert function_exported?(Xdk.Users, :get_muting, 2) or
               function_exported?(Xdk.Users, :get_muting, 3)
    end

    test "mute_user function exists" do
      Code.ensure_loaded!(Xdk.Users)
      assert function_exported?(Xdk.Users, :mute_user, 2)
    end

    test "get_me function exists" do
      Code.ensure_loaded!(Xdk.Users)

      assert function_exported?(Xdk.Users, :get_me, 1) or
               function_exported?(Xdk.Users, :get_me, 2)
    end

    test "get_followers function exists" do
      Code.ensure_loaded!(Xdk.Users)

      assert function_exported?(Xdk.Users, :get_followers, 2) or
               function_exported?(Xdk.Users, :get_followers, 3)
    end

    test "unlike_post function exists" do
      Code.ensure_loaded!(Xdk.Users)
      assert function_exported?(Xdk.Users, :unlike_post, 3)
    end

    test "get_reposts_of_me function exists" do
      Code.ensure_loaded!(Xdk.Users)

      assert function_exported?(Xdk.Users, :get_reposts_of_me, 1) or
               function_exported?(Xdk.Users, :get_reposts_of_me, 2)
    end

    test "search function exists" do
      Code.ensure_loaded!(Xdk.Users)

      assert function_exported?(Xdk.Users, :search, 1) or
               function_exported?(Xdk.Users, :search, 2)
    end

    test "unfollow_list function exists" do
      Code.ensure_loaded!(Xdk.Users)
      assert function_exported?(Xdk.Users, :unfollow_list, 3)
    end

    test "get_by_username function exists" do
      Code.ensure_loaded!(Xdk.Users)

      assert function_exported?(Xdk.Users, :get_by_username, 2) or
               function_exported?(Xdk.Users, :get_by_username, 3)
    end

    test "delete_bookmark function exists" do
      Code.ensure_loaded!(Xdk.Users)
      assert function_exported?(Xdk.Users, :delete_bookmark, 3)
    end

    test "get_timeline function exists" do
      Code.ensure_loaded!(Xdk.Users)

      assert function_exported?(Xdk.Users, :get_timeline, 2) or
               function_exported?(Xdk.Users, :get_timeline, 3)
    end

    test "get_followed_lists function exists" do
      Code.ensure_loaded!(Xdk.Users)

      assert function_exported?(Xdk.Users, :get_followed_lists, 2) or
               function_exported?(Xdk.Users, :get_followed_lists, 3)
    end

    test "follow_list function exists" do
      Code.ensure_loaded!(Xdk.Users)
      assert function_exported?(Xdk.Users, :follow_list, 2)
    end

    test "get_bookmarks function exists" do
      Code.ensure_loaded!(Xdk.Users)

      assert function_exported?(Xdk.Users, :get_bookmarks, 2) or
               function_exported?(Xdk.Users, :get_bookmarks, 3)
    end

    test "create_bookmark function exists" do
      Code.ensure_loaded!(Xdk.Users)
      assert function_exported?(Xdk.Users, :create_bookmark, 2)
    end
  end
end
