# AUTO-GENERATED FILE - DO NOT EDIT
# This file was automatically generated by the XDK build tool.
# Any manual changes will be overwritten on the next generation.
defmodule Xdk.WebhooksTest do
  use ExUnit.Case, async: true

  describe "module structure" do
    test "module exists" do
      assert Code.ensure_loaded?(Xdk.Webhooks)
    end

    test "get_stream_links function exists" do
      Code.ensure_loaded!(Xdk.Webhooks)
      assert function_exported?(Xdk.Webhooks, :get_stream_links, 1)
    end

    test "create_webhook_replay_job function exists" do
      Code.ensure_loaded!(Xdk.Webhooks)
      assert function_exported?(Xdk.Webhooks, :create_webhook_replay_job, 1)
    end

    test "validate function exists" do
      Code.ensure_loaded!(Xdk.Webhooks)
      assert function_exported?(Xdk.Webhooks, :validate, 2)
    end

    test "delete function exists" do
      Code.ensure_loaded!(Xdk.Webhooks)
      assert function_exported?(Xdk.Webhooks, :delete, 2)
    end

    test "create_stream_link function exists" do
      Code.ensure_loaded!(Xdk.Webhooks)

      assert function_exported?(Xdk.Webhooks, :create_stream_link, 2) or
               function_exported?(Xdk.Webhooks, :create_stream_link, 3)
    end

    test "delete_stream_link function exists" do
      Code.ensure_loaded!(Xdk.Webhooks)
      assert function_exported?(Xdk.Webhooks, :delete_stream_link, 2)
    end

    test "get function exists" do
      Code.ensure_loaded!(Xdk.Webhooks)

      assert function_exported?(Xdk.Webhooks, :get, 1) or
               function_exported?(Xdk.Webhooks, :get, 2)
    end

    test "create function exists" do
      Code.ensure_loaded!(Xdk.Webhooks)
      assert function_exported?(Xdk.Webhooks, :create, 1)
    end
  end
end
